---
secrets:
  kittens:
    key: kittens
    type: kittens
    owner: ''
    playbook:
    externally_usable: false
    kind: latest_at_deployment_start
  spn_copilot_cli_signing:
    key: spn_copilot_cli_signing
    type: azure_spn
    owner: "@github/sae-ps"
    playbook: https://thehub.github.com/security/security-operations/secrets/secrets-rotation/azure-spn
    externally_usable: true
    kind: latest_at_deployment_start
  spn_copilot_cli_signing_client_id:
    key: spn_copilot_cli_signing_client_id
    type: azure_spn
    owner: "@github/sae-ps"
    playbook: https://thehub.github.com/security/security-operations/secrets/secrets-rotation/azure-spn
    externally_usable: true
    kind: latest_at_deployment_start
  spn_copilot_cli_signing_tenant_id:
    key: spn_copilot_cli_signing_tenant_id
    type: azure_spn
    owner: "@github/sae-ps"
    playbook: https://thehub.github.com/security/security-operations/secrets/secrets-rotation/azure-spn
    externally_usable: true
    kind: latest_at_deployment_start
